### ISSUE TITLE
Configurar TTS always on con nick de usuario opcional

### ISSUE THREAD

**Issue by Pythonesa** [chrisvill2312/obs-chat#10]
COMO usuario
QUIERO tener la opción de que al estar activo el tts me permita configurar si lee el nombre del usuario o solamente el mensaje
Y que el mensaje leído por el tts tenga el formato: nick dijo mensaje
PARA saber quien envía un mensaje sin tener que leer el chat

**Comment by chrisvdev** [comment]
Feature completa, se usa mediante la param tts_mentions y los valores posibles son "true" o "false" para activar y desactivar respectivamente.
