### ISSUE TITLE
BUG: Cuando usas el Speak se come la variante siempre

### ISSUE THREAD

**Issue by chrisvdev** [chrisvill2312/obs-chat#15]
al hacer "!speak acento palabra1 palabra2" se come la palabra1 pensando que es la variante

**Comment by Pythonesa** [comment]
cuando haces "!speak acento variante palabra1 palabra2" también se come la palabra1
Ejemplo: !speak es-CO2 primera segunda" solamente lee "segunda"

**Comment by chrisvdev** [comment]
Resuelto en commit https://github.com/chrisvdev/obs-chat/commit/0fde5c794183435e7fa3c8e49c8c9d215e6c55b4
