### ISSUE TITLE
MEJORA: Configuración TTS

### ISSUE THREAD

**Issue by Pythonesa** [chrisvill2312/obs-chat#16]
_COMO_ Analista Funcional
_QUIERO_ que se mejore la funcionalidad de configuración del TTS
_PARA_ que no se ignoren configuraciones de los usuarios

**Descripción:**
Se socializo la implementación de un event listener para el evento "storage" que permita escuchar cuando se modifica la información almacenada en el local storage de forma exitosa y evitar perder mensajes de configuración que actualmente no están siendo guardados.
También se socializo la implementación del mantenimiento de las configuraciones en memoria para su lectura y así no consultar con peticiones de lectura el local storage del navegador.

**Links a documentación útil:**
[Event Listener para el evento storage.](https://developer.mozilla.org/en-US/docs/Web/API/Web_Storage_API/Using_the_Web_Storage_API#responding_to_storage_changes_with_the_storageevent)

**Comment by chrisvdev** [comment]
Arreglado en commit https://github.com/chrisvdev/obs-chat/commit/492aca5a68e50811ae1529a1981095bcad93c75d
Chas Gracias <3
