### ISSUE TITLE
FEATURE: Emoticono de Alita

### ISSUE THREAD

**Issue by Pythonesa** [chrisvill2312/obs-chat#22]
COMO tía de Alita
QUIERO que el tts diga "emoticono de alita" cuando se escriba ":3"
PARA que Alita sea feliz con su emoticon

**Comment by chrisvdev** [comment]
Solucionado e imprentado en https://github.com/chrisvdev/obs-chat/commit/2a59c64fa674286c55c459a5968df028990ed0b9
