### ISSUE TITLE
FEAT: Restricción de usuarios por mods

### ISSUE THREAD

**Issue by ghost** [chrisvill2312/obs-chat#24]
COMO moderadora furiosa
QUIERO que los moderadores puedan silenciar usuarios del TTS con un comando del tipo -> !silenciar Nick_de_usuario
PARA que el TTS no lea los mensajes del comando !speak del usuario silenciado
Y que el TTS no lea los mensajes del usuario silenciado cuando está en modo ALWAYS ON

**Comment by chrisvdev** [comment]
Solucionado e implementado en https://github.com/chrisvdev/obs-chat/commit/a61103257cc189dfe2aed9a92d19299cac2f4d9f
