### ISSUE TITLE
Soporte para Firefox

### ISSUE THREAD

**Issue by felixicaza** [chrisvill2312/obs-chat#5]
Debido que se está utilizando [Navigation API](https://developer.mozilla.org/en-US/docs/Web/API/Navigation_API) la cual [no tiene soporte para Firefox](https://caniuse.com/mdn-api_navigation), los usuarios que deseen hacer pruebas en este navegador no podrán utilizar el chat.

Archivo: [use_connect_websocket_to_twitch_irc.js](https://github.com/chrisvdev/obs-chat/blob/main/src/hooks/use_connect_websocket_to_twitch_irc.js)

Código:

```js
if (!accessToken) {
    clientId &&
      // eslint-disable-next-line no-undef
      navigation.navigate(
        // navigation object exists on the supported browsers
        // eslint-disable-next-line max-len, no-unneeded-ternary
        `https://id.twitch.tv/oauth2/authorize?response_type=token&client_id=${clientId}&redirect_uri=${
          redirectUri || 'http://localhost:5173/&scope=chat%3Aread'
        }`
      )
  }
```

Error en Firefox:

![Error para Firefox](https://github.com/chrisvdev/obs-chat/assets/38303370/db82600c-3fea-477a-a78f-d0888bb92ac8)

**Comment by chrisvdev** [comment]
Nada que agregar al respecto, ahi vi la PR y me parece perfecta la solución. Gracias!

**Comment by chrisvdev** [comment]
Solucionado PR mediante https://github.com/chrisvdev/obs-chat/pull/6 se cierra la Issue y da por solucionada.
