### ISSUE TITLE
Opción para cambiarle el acento a un usuario

### ISSUE THREAD

**Issue by felixicaza** [chrisvill2312/obs-chat#9]
[Modo troll]: Una configuración para cambiar el acento a un usuario en específico.

Por ejemplo:

```
!speak -config jp-JP @chrisvdev
```

Mensaje:

```
El usuario @felixicaza ha establecido el acento jp-JP a @chrisvdev.
```

Pd: Se podría añadir a los canjes del canal.

**Comment by chrisvdev** [comment]
Ya implementado!
